### ISSUE TITLE
New Hex Validation?

### ISSUE THREAD

**Issue by rmorshea** [rmorshea/matplotlib#2]
``` python
import re
_color_re = re.compile(r'#[a-fA-F0-9]{3}(?:[a-fA-F0-9]{3})?$')

invalid_colors = ['áfaef', '#FFF', '#0SX#$S'] # doesn't check for : (0,0,0), (0.45,0.3), (()), {}, True
print [_color_re.match(ivc) for ivc in invalid_colors]

Out[1]: [None, <_sre.SRE_Match at 0x105c83098>, None]
```

This was done quickly (hence the matched, but false input). It might be better though.

**Comment by rmorshea** [comment]
@AndreLobato, if you get the chance let me know if you think this might be a better method of hex validation on the color [`TraitType`](https://github.com/rmorshea/matplotlib/blob/mpl_traitlets/lib/matplotlib/traitlets.py) you wrote. I'll go through it myself at some point if you don't get to it since this is what's been implemented in the [ipython widgets](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/trait_types.py).

**Comment by AndreLobato** [comment]
Yes, its much better, faster and elegant. I will update the pull request. Thanks.

**Comment by rmorshea** [comment]
@AndreLobato, I was also told that `"#FFF"` is valid and ==> `"#FFFFFF". So it'd be great if you could correct that in the tests as well.

**Comment by AndreLobato** [comment]
Has been done.

**Comment by AndreLobato** [comment]
Hi there I was just folowing the conversation on the main merge attempt, looks like my last commit didnt made trough, do I need to create a new pull request in this situation?

**Comment by rmorshea** [comment]
I'd already accepted the pull request when I created the issue so it requires a new pull request. However I can do that as well, I just didn't have internet access on the plane yesterday.

**Comment by AndreLobato** [comment]
Sweet i am still on transit back from scipy when I get home will fix the alpha mistake as well.  

Regards

**Comment by rmorshea** [comment]
I think I'll wait to pull until those changes are in. Just let me know when they're in and I'll merge.
